# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
          - id: flake8
            language_version: python3.8
            name: flake8
            entry: flake8
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.6.4
      hooks:
          - id: isort
            language_version: python3.8
    - repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
          - id: black
            language_version: python3.8
